import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Header from "../components/Header";
import TopRelativeItem from "../components/TopRelated/TopRelativeItem";
import { useGetAllCoinQuery } from "../state/services/coin";

const Coins = () => {
  const router = useRouter();
  const { search } = router.query;
  const { data, isLoading, isError } = useGetAllCoinQuery();
  if (isLoading) return <div>Loading</div>;

  if (isError) return <div>Error</div>;

  return (
    <div>
      <Head>
        <title>Coin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container my-4 text-gray-900 ">
          <Header name="Coins" />
          <div
            className="grid grid-cols-4 "
          >
            {data
              ?.filter((item) =>
                item.name.toLowerCase().startsWith(search?.toLowerCase())
              )
              .map((item) => (
                <TopRelativeItem key={item.id} {...item} />
              ))}
          </div>
        </div>
      </main>{" "}
    </div>
  );
};

export default Coins;
